
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 职业类型
 */
const (
    /**
     * 通用
     */
    BattleRoleType_General = 0;
    /**
     * 战士
     */
    BattleRoleType_Berserker = 1;
    /**
     * 法师
     */
    BattleRoleType_FlameMage = 2;
    /**
     * 弓手
     */
    BattleRoleType_Ranger = 3;
)

