
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 元素种类
 */
const (
    /**
     * 无
     */
    BattleElementType_None = 0;
    /**
     * 黑暗
     */
    BattleElementType_Darkness = 1;
    /**
     * 火
     */
    BattleElementType_Fire = 2;
    /**
     * 神圣
     */
    BattleElementType_Holy = 4;
    /**
     * 魔法
     */
    BattleElementType_Magic = 8;
    /**
     * 自然
     */
    BattleElementType_Nature = 16;
    /**
     * 吸血
     */
    BattleElementType_Vampiric = 32;
)

