
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 物品类型
 */
const (
    /**
     * 背包
     */
    BattleItemType_Backpack = 1;
    /**
     * 护甲
     */
    BattleItemType_Armor = 2;
    /**
     * 配饰
     */
    BattleItemType_Accessory = 4;
    /**
     * 食物
     */
    BattleItemType_Food = 8;
    /**
     * 宝石
     */
    BattleItemType_Gemstone = 16;
    /**
     * 手套
     */
    BattleItemType_Gloves = 32;
    /**
     * 头盔
     */
    BattleItemType_Helmet = 64;
    /**
     * 近战武器
     */
    BattleItemType_MeleeWeapon = 128;
    /**
     * 宠物
     */
    BattleItemType_Pet = 256;
    /**
     * 卡牌
     */
    BattleItemType_Card = 512;
    /**
     * 药水
     */
    BattleItemType_Potion = 1024;
    /**
     * 远程武器
     */
    BattleItemType_RangedWeapon = 2048;
    /**
     * 盾牌
     */
    BattleItemType_Shield = 4096;
    /**
     * 鞋子
     */
    BattleItemType_Boots = 8192;
)

