
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type BattleTBGoodsStar struct {
    _dataMap map[int32]*GoodsStar
    _dataList []*GoodsStar
}

func NewBattleTBGoodsStar(_buf []map[string]interface{}) (*BattleTBGoodsStar, error) {
    _dataList := make([]*GoodsStar, 0, len(_buf))
    dataMap := make(map[int32]*GoodsStar)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGoodsStar(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &BattleTBGoodsStar{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *BattleTBGoodsStar) GetDataMap() map[int32]*GoodsStar {
    return table._dataMap
}

func (table *BattleTBGoodsStar) GetDataList() []*GoodsStar {
    return table._dataList
}

func (table *BattleTBGoodsStar) Get(key int32) *GoodsStar {
    return table._dataMap[key]
}


