
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type BattleTBRobot struct {
    _dataMap map[int32]*Robot
    _dataList []*Robot
}

func NewBattleTBRobot(_buf []map[string]interface{}) (*BattleTBRobot, error) {
    _dataList := make([]*Robot, 0, len(_buf))
    dataMap := make(map[int32]*Robot)

    for _, _ele_ := range _buf {
        if _v, err2 := NewRobot(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &BattleTBRobot{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *BattleTBRobot) GetDataMap() map[int32]*Robot {
    return table._dataMap
}

func (table *BattleTBRobot) GetDataList() []*Robot {
    return table._dataList
}

func (table *BattleTBRobot) Get(key int32) *Robot {
    return table._dataMap[key]
}


