
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 品质类型
 */
const (
    /**
     * 普通
     */
    BattleItemQuality_Common = 0;
    /**
     * 罕见
     */
    BattleItemQuality_Rare = 1;
    /**
     * 稀有
     */
    BattleItemQuality_Epic = 2;
    /**
     * 传说
     */
    BattleItemQuality_Legendary = 3;
    /**
     * 神级
     */
    BattleItemQuality_Mythical = 4;
    /**
     * 特别
     */
    BattleItemQuality_Special = 5;
)

