
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type BattleTBSeasonRewards struct {
    _dataMap map[int32]*SeasonRewards
    _dataList []*SeasonRewards
}

func NewBattleTBSeasonRewards(_buf []map[string]interface{}) (*BattleTBSeasonRewards, error) {
    _dataList := make([]*SeasonRewards, 0, len(_buf))
    dataMap := make(map[int32]*SeasonRewards)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSeasonRewards(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &BattleTBSeasonRewards{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *BattleTBSeasonRewards) GetDataMap() map[int32]*SeasonRewards {
    return table._dataMap
}

func (table *BattleTBSeasonRewards) GetDataList() []*SeasonRewards {
    return table._dataList
}

func (table *BattleTBSeasonRewards) Get(key int32) *SeasonRewards {
    return table._dataMap[key]
}


