
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type BattleTBGLConst struct {
    _dataMap map[int32]*GLConst
    _dataList []*GLConst
}

func NewBattleTBGLConst(_buf []map[string]interface{}) (*BattleTBGLConst, error) {
    _dataList := make([]*GLConst, 0, len(_buf))
    dataMap := make(map[int32]*GLConst)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGLConst(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.PoisonDamage] = _v
        }
    }
    return &BattleTBGLConst{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *BattleTBGLConst) GetDataMap() map[int32]*GLConst {
    return table._dataMap
}

func (table *BattleTBGLConst) GetDataList() []*GLConst {
    return table._dataList
}

func (table *BattleTBGLConst) Get(key int32) *GLConst {
    return table._dataMap[key]
}


