
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 摆放技能条件
 */
const (
    /**
     * 无
     */
    BattlePSkillCondition_None = 0;
    /**
     * 背包格子空
     */
    BattlePSkillCondition_EmptyBag = 1;
    /**
     * 除本身
     */
    BattlePSkillCondition_ExceptSelf = 2;
    /**
     * 带星
     */
    BattlePSkillCondition_HaveStar = 4;
    /**
     * 所有物体
     */
    BattlePSkillCondition_Any = 8;
    /**
     * 战斗开始时
     */
    BattlePSkillCondition_StartBattle = 16;
    /**
     * 宠物类
     */
    BattlePSkillCondition_Pets = 32;
    /**
     * 神圣类
     */
    BattlePSkillCondition_Sacred = 64;
    /**
     * 黑暗类
     */
    BattlePSkillCondition_Darkness = 128;
    /**
     * 火
     */
    BattlePSkillCondition_Fire = 256;
    /**
     * 武器类
     */
    BattlePSkillCondition_Weapons = 512;
    /**
     * 药水类
     */
    BattlePSkillCondition_Potions = 1024;
    /**
     * 石子类
     */
    BattlePSkillCondition_Stone = 2048;
    /**
     * 食物类
     */
    BattlePSkillCondition_Food = 4096;
    /**
     * 冷却类
     */
    BattlePSkillCondition_Cooldown = 8192;
    /**
     * 几率触发类
     */
    BattlePSkillCondition_RateActive = 16384;
    /**
     * 护盾类
     */
    BattlePSkillCondition_Armor = 32768;
    /**
     * 吸血类
     */
    BattlePSkillCondition_LifeSteal = 65536;
    /**
     * 魔法类
     */
    BattlePSkillCondition_Magic = 131072;
)

