
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type BattleTBRank struct {
    _dataMap map[int32]*Rank
    _dataList []*Rank
}

func NewBattleTBRank(_buf []map[string]interface{}) (*BattleTBRank, error) {
    _dataList := make([]*Rank, 0, len(_buf))
    dataMap := make(map[int32]*Rank)

    for _, _ele_ := range _buf {
        if _v, err2 := NewRank(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.RankId] = _v
        }
    }
    return &BattleTBRank{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *BattleTBRank) GetDataMap() map[int32]*Rank {
    return table._dataMap
}

func (table *BattleTBRank) GetDataList() []*Rank {
    return table._dataList
}

func (table *BattleTBRank) Get(key int32) *Rank {
    return table._dataMap[key]
}


