
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type GLConst struct {
    PoisonDamage int32
    TestMaxHp float32
    TestMaxPower float32
    MaxInjuredPercent float32
}

const TypeId_GLConst = 829359486

func (*GLConst) GetTypeId() int32 {
    return 829359486
}

func NewGLConst(_buf map[string]interface{}) (_v *GLConst, err error) {
    _v = &GLConst{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["PoisonDamage"].(float64); !_ok_ { err = errors.New("PoisonDamage error"); return }; _v.PoisonDamage = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["TestMaxHp"].(float64); !_ok_ { err = errors.New("TestMaxHp error"); return }; _v.TestMaxHp = float32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["TestMaxPower"].(float64); !_ok_ { err = errors.New("TestMaxPower error"); return }; _v.TestMaxPower = float32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["MaxInjuredPercent"].(float64); !_ok_ { err = errors.New("MaxInjuredPercent error"); return }; _v.MaxInjuredPercent = float32(_tempNum_) }
    return
}

