
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type Robot struct {
    Id int32
    RoleId int32
    Score int32
    Military int32
}

const TypeId_Robot = 79133258

func (*Robot) GetTypeId() int32 {
    return 79133258
}

func NewRobot(_buf map[string]interface{}) (_v *Robot, err error) {
    _v = &Robot{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["roleId"].(float64); !_ok_ { err = errors.New("roleId error"); return }; _v.RoleId = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["score"].(float64); !_ok_ { err = errors.New("score error"); return }; _v.Score = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["military"].(float64); !_ok_ { err = errors.New("military error"); return }; _v.Military = int32(_tempNum_) }
    return
}

