
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SeasonRewards struct {
    Id int32
    Title string
    MinRanking int32
    MaxRanking int32
    Rewards string
}

const TypeId_SeasonRewards = 376929953

func (*SeasonRewards) GetTypeId() int32 {
    return 376929953
}

func NewSeasonRewards(_buf map[string]interface{}) (_v *SeasonRewards, err error) {
    _v = &SeasonRewards{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; if _v.Title, _ok_ = _buf["title"].(string); !_ok_ { err = errors.New("title error"); return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["min_ranking"].(float64); !_ok_ { err = errors.New("min_ranking error"); return }; _v.MinRanking = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["max_ranking"].(float64); !_ok_ { err = errors.New("max_ranking error"); return }; _v.MaxRanking = int32(_tempNum_) }
    { var _ok_ bool; if _v.Rewards, _ok_ = _buf["rewards"].(string); !_ok_ { err = errors.New("rewards error"); return } }
    return
}

