
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ShopGold struct {
    Id int32
    Number int32
    Gold int32
    IntervalMins int32
}

const TypeId_ShopGold = -281032554

func (*ShopGold) GetTypeId() int32 {
    return -281032554
}

func NewShopGold(_buf map[string]interface{}) (_v *ShopGold, err error) {
    _v = &ShopGold{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["number"].(float64); !_ok_ { err = errors.New("number error"); return }; _v.Number = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["gold"].(float64); !_ok_ { err = errors.New("gold error"); return }; _v.Gold = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["interval_mins"].(float64); !_ok_ { err = errors.New("interval_mins error"); return }; _v.IntervalMins = int32(_tempNum_) }
    return
}

