
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ShopRefresh struct {
    Id int32
    Number int32
    RefreshType int32
    Price int32
}

const TypeId_ShopRefresh = -468265243

func (*ShopRefresh) GetTypeId() int32 {
    return -468265243
}

func NewShopRefresh(_buf map[string]interface{}) (_v *ShopRefresh, err error) {
    _v = &ShopRefresh{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["number"].(float64); !_ok_ { err = errors.New("number error"); return }; _v.Number = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["refreshType"].(float64); !_ok_ { err = errors.New("refreshType error"); return }; _v.RefreshType = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["price"].(float64); !_ok_ { err = errors.New("price error"); return }; _v.Price = int32(_tempNum_) }
    return
}

