
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type TreasureBox struct {
    RankId int32
    Number int32
    WoodProp int32
    IronyProp int32
    GoldProp int32
}

const TypeId_TreasureBox = 278517884

func (*TreasureBox) GetTypeId() int32 {
    return 278517884
}

func NewTreasureBox(_buf map[string]interface{}) (_v *TreasureBox, err error) {
    _v = &TreasureBox{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["rankId"].(float64); !_ok_ { err = errors.New("rankId error"); return }; _v.RankId = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["number"].(float64); !_ok_ { err = errors.New("number error"); return }; _v.Number = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["woodProp"].(float64); !_ok_ { err = errors.New("woodProp error"); return }; _v.WoodProp = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["ironyProp"].(float64); !_ok_ { err = errors.New("ironyProp error"); return }; _v.IronyProp = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["goldProp"].(float64); !_ok_ { err = errors.New("goldProp error"); return }; _v.GoldProp = int32(_tempNum_) }
    return
}

