
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type TreasureBoxGoods struct {
    Id int32
    Type int32
    GoodsId int32
    Number int32
    Prop int32
}

const TypeId_TreasureBoxGoods = -712852422

func (*TreasureBoxGoods) GetTypeId() int32 {
    return -712852422
}

func NewTreasureBoxGoods(_buf map[string]interface{}) (_v *TreasureBoxGoods, err error) {
    _v = &TreasureBoxGoods{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["type"].(float64); !_ok_ { err = errors.New("type error"); return }; _v.Type = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["goodsId"].(float64); !_ok_ { err = errors.New("goodsId error"); return }; _v.GoodsId = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["number"].(float64); !_ok_ { err = errors.New("number error"); return }; _v.Number = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["prop"].(float64); !_ok_ { err = errors.New("prop error"); return }; _v.Prop = int32(_tempNum_) }
    return
}

