
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 职业类型
    /// </summary>
    public enum RoleType
    {
        /// <summary>
        /// 通用
        /// </summary>
        General = 0,
        /// <summary>
        /// 战士
        /// </summary>
        Berserker = 1,
        /// <summary>
        /// 法师
        /// </summary>
        FlameMage = 2,
        /// <summary>
        /// 弓手
        /// </summary>
        Ranger = 3,
    }

} 

