
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 摆放技能条件
    /// </summary>
    [System.Flags]
    public enum PSkillCondition
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 背包格子空
        /// </summary>
        EmptyBag = 1,
        /// <summary>
        /// 除本身
        /// </summary>
        ExceptSelf = 2,
        /// <summary>
        /// 带星
        /// </summary>
        HaveStar = 4,
        /// <summary>
        /// 所有物体
        /// </summary>
        Any = 8,
        /// <summary>
        /// 战斗开始时
        /// </summary>
        StartBattle = 16,
        /// <summary>
        /// 宠物类
        /// </summary>
        Pets = 32,
        /// <summary>
        /// 神圣类
        /// </summary>
        Sacred = 64,
        /// <summary>
        /// 黑暗类
        /// </summary>
        Darkness = 128,
        /// <summary>
        /// 火
        /// </summary>
        Fire = 256,
        /// <summary>
        /// 武器类
        /// </summary>
        Weapons = 512,
        /// <summary>
        /// 药水类
        /// </summary>
        Potions = 1024,
        /// <summary>
        /// 石子类
        /// </summary>
        Stone = 2048,
        /// <summary>
        /// 食物类
        /// </summary>
        Food = 4096,
        /// <summary>
        /// 冷却类
        /// </summary>
        Cooldown = 8192,
        /// <summary>
        /// 几率触发类
        /// </summary>
        RateActive = 16384,
        /// <summary>
        /// 护盾类
        /// </summary>
        Armor = 32768,
        /// <summary>
        /// 吸血类
        /// </summary>
        LifeSteal = 65536,
        /// <summary>
        /// 魔法类
        /// </summary>
        Magic = 131072,
    }

} 

