
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 元素种类
    /// </summary>
    [System.Flags]
    public enum ElementType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 黑暗
        /// </summary>
        Darkness = 1,
        /// <summary>
        /// 火
        /// </summary>
        Fire = 2,
        /// <summary>
        /// 神圣
        /// </summary>
        Holy = 4,
        /// <summary>
        /// 魔法
        /// </summary>
        Magic = 8,
        /// <summary>
        /// 自然
        /// </summary>
        Nature = 16,
        /// <summary>
        /// 吸血
        /// </summary>
        Vampiric = 32,
    }

} 

