
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TBRank
{
    private readonly System.Collections.Generic.Dictionary<int, Rank> _dataMap;
    private readonly System.Collections.Generic.List<Rank> _dataList;
    
    public TBRank(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Rank>();
        _dataList = new System.Collections.Generic.List<Rank>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Rank _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Rank.DeserializeRank(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.RankId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Rank> DataMap => _dataMap;
    public System.Collections.Generic.List<Rank> DataList => _dataList;

    public Rank GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Rank Get(int key) => _dataMap[key];
    public Rank this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

