
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 品质类型
    /// </summary>
    public enum ItemQuality
    {
        /// <summary>
        /// 普通
        /// </summary>
        Common = 0,
        /// <summary>
        /// 罕见
        /// </summary>
        Rare = 1,
        /// <summary>
        /// 稀有
        /// </summary>
        Epic = 2,
        /// <summary>
        /// 传说
        /// </summary>
        Legendary = 3,
        /// <summary>
        /// 神级
        /// </summary>
        Mythical = 4,
        /// <summary>
        /// 特别
        /// </summary>
        Special = 5,
    }

} 

