
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 摆放技能种类
    /// </summary>
    public enum PSkillKind
    {
        /// <summary>
        /// 种类A
        /// </summary>
        A = 0,
        /// <summary>
        /// 种类B
        /// </summary>
        B = 1,
    }

} 

