
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TBGoodsStar
{
    private readonly System.Collections.Generic.Dictionary<int, GoodsStar> _dataMap;
    private readonly System.Collections.Generic.List<GoodsStar> _dataList;
    
    public TBGoodsStar(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GoodsStar>();
        _dataList = new System.Collections.Generic.List<GoodsStar>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GoodsStar _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = GoodsStar.DeserializeGoodsStar(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GoodsStar> DataMap => _dataMap;
    public System.Collections.Generic.List<GoodsStar> DataList => _dataList;

    public GoodsStar GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GoodsStar Get(int key) => _dataMap[key];
    public GoodsStar this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

