
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TBTreasureBox
{
    private readonly System.Collections.Generic.Dictionary<int, TreasureBox> _dataMap;
    private readonly System.Collections.Generic.List<TreasureBox> _dataList;
    
    public TBTreasureBox(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TreasureBox>();
        _dataList = new System.Collections.Generic.List<TreasureBox>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TreasureBox _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = TreasureBox.DeserializeTreasureBox(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.RankId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TreasureBox> DataMap => _dataMap;
    public System.Collections.Generic.List<TreasureBox> DataList => _dataList;

    public TreasureBox GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TreasureBox Get(int key) => _dataMap[key];
    public TreasureBox this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

