
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TBItemStar
{
    private readonly System.Collections.Generic.Dictionary<int, ItemStar> _dataMap;
    private readonly System.Collections.Generic.List<ItemStar> _dataList;
    
    public TBItemStar(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemStar>();
        _dataList = new System.Collections.Generic.List<ItemStar>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ItemStar _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ItemStar.DeserializeItemStar(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemStar> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemStar> DataList => _dataList;

    public ItemStar GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemStar Get(int key) => _dataMap[key];
    public ItemStar this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

