
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 物品类型
    /// </summary>
    [System.Flags]
    public enum ItemType
    {
        /// <summary>
        /// 背包
        /// </summary>
        Backpack = 1,
        /// <summary>
        /// 护甲
        /// </summary>
        Armor = 2,
        /// <summary>
        /// 配饰
        /// </summary>
        Accessory = 4,
        /// <summary>
        /// 食物
        /// </summary>
        Food = 8,
        /// <summary>
        /// 宝石
        /// </summary>
        Gemstone = 16,
        /// <summary>
        /// 手套
        /// </summary>
        Gloves = 32,
        /// <summary>
        /// 头盔
        /// </summary>
        Helmet = 64,
        /// <summary>
        /// 近战武器
        /// </summary>
        MeleeWeapon = 128,
        /// <summary>
        /// 宠物
        /// </summary>
        Pet = 256,
        /// <summary>
        /// 卡牌
        /// </summary>
        Card = 512,
        /// <summary>
        /// 药水
        /// </summary>
        Potion = 1024,
        /// <summary>
        /// 远程武器
        /// </summary>
        RangedWeapon = 2048,
        /// <summary>
        /// 盾牌
        /// </summary>
        Shield = 4096,
        /// <summary>
        /// 鞋子
        /// </summary>
        Boots = 8192,
    }

} 

