
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GLConst : Luban.BeanBase
{
    public GLConst(JSONNode _buf) 
    {
        { if(!_buf["PoisonDamage"].IsNumber) { throw new SerializationException(); }  PoisonDamage = _buf["PoisonDamage"]; }
        { if(!_buf["TestMaxHp"].IsNumber) { throw new SerializationException(); }  TestMaxHp = _buf["TestMaxHp"]; }
        { if(!_buf["TestMaxPower"].IsNumber) { throw new SerializationException(); }  TestMaxPower = _buf["TestMaxPower"]; }
        { if(!_buf["MaxInjuredPercent"].IsNumber) { throw new SerializationException(); }  MaxInjuredPercent = _buf["MaxInjuredPercent"]; }
    }

    public static GLConst DeserializeGLConst(JSONNode _buf)
    {
        return new GLConst(_buf);
    }

    /// <summary>
    /// 每点毒伤害
    /// </summary>
    public readonly int PoisonDamage;
    /// <summary>
    /// 测试最大生命值
    /// </summary>
    public readonly float TestMaxHp;
    /// <summary>
    /// 测试最大力度
    /// </summary>
    public readonly float TestMaxPower;
    /// <summary>
    /// 最大免伤百分比
    /// </summary>
    public readonly float MaxInjuredPercent;
   
    public const int __ID__ = 829359486;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "PoisonDamage:" + PoisonDamage + ","
        + "TestMaxHp:" + TestMaxHp + ","
        + "TestMaxPower:" + TestMaxPower + ","
        + "MaxInjuredPercent:" + MaxInjuredPercent + ","
        + "}";
    }
}

}
