
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GoodsStar : Luban.BeanBase
{
    public GoodsStar(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["star"].IsNumber) { throw new SerializationException(); }  Star = _buf["star"]; }
        { if(!_buf["common"].IsNumber) { throw new SerializationException(); }  Common = _buf["common"]; }
        { if(!_buf["rare"].IsNumber) { throw new SerializationException(); }  Rare = _buf["rare"]; }
        { if(!_buf["epic"].IsNumber) { throw new SerializationException(); }  Epic = _buf["epic"]; }
        { if(!_buf["legendary"].IsNumber) { throw new SerializationException(); }  Legendary = _buf["legendary"]; }
        { if(!_buf["mythical"].IsNumber) { throw new SerializationException(); }  Mythical = _buf["mythical"]; }
        { if(!_buf["special"].IsNumber) { throw new SerializationException(); }  Special = _buf["special"]; }
    }

    public static GoodsStar DeserializeGoodsStar(JSONNode _buf)
    {
        return new GoodsStar(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 星级
    /// </summary>
    public readonly int Star;
    /// <summary>
    /// 普通
    /// </summary>
    public readonly int Common;
    /// <summary>
    /// 罕见
    /// </summary>
    public readonly int Rare;
    /// <summary>
    /// 稀有
    /// </summary>
    public readonly int Epic;
    /// <summary>
    /// 传说
    /// </summary>
    public readonly int Legendary;
    /// <summary>
    /// 神级
    /// </summary>
    public readonly int Mythical;
    /// <summary>
    /// 特别
    /// </summary>
    public readonly int Special;
   
    public const int __ID__ = -896428376;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "star:" + Star + ","
        + "common:" + Common + ","
        + "rare:" + Rare + ","
        + "epic:" + Epic + ","
        + "legendary:" + Legendary + ","
        + "mythical:" + Mythical + ","
        + "special:" + Special + ","
        + "}";
    }
}

}
