
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemStar : Luban.BeanBase
{
    public ItemStar(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["itemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["itemId"]; }
        { if(!_buf["evlack"].IsNumber) { throw new SerializationException(); }  Evlack = _buf["evlack"]; }
        { if(!_buf["avlcmb"].IsNumber) { throw new SerializationException(); }  Avlcmb = _buf["avlcmb"]; }
        { var __json0 = _buf["skillList"]; if(!__json0.IsArray) { throw new SerializationException(); } SkillList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillList.Add(__v0); }   }
        { if(!_buf["weaponSlotSkill"].IsNumber) { throw new SerializationException(); }  WeaponSlotSkill = _buf["weaponSlotSkill"]; }
        { if(!_buf["armorSlotSkill"].IsNumber) { throw new SerializationException(); }  ArmorSlotSkill = _buf["armorSlotSkill"]; }
        { if(!_buf["bagSlotSkill"].IsNumber) { throw new SerializationException(); }  BagSlotSkill = _buf["bagSlotSkill"]; }
        { if(!_buf["propertyId"].IsNumber) { throw new SerializationException(); }  PropertyId = _buf["propertyId"]; }
        { if(!_buf["des"].IsString) { throw new SerializationException(); }  Des = _buf["des"]; }
    }

    public static ItemStar DeserializeItemStar(JSONNode _buf)
    {
        return new ItemStar(_buf);
    }

    /// <summary>
    /// starId
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// uid
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 秒伤
    /// </summary>
    public readonly int Evlack;
    /// <summary>
    /// 战力
    /// </summary>
    public readonly int Avlcmb;
    /// <summary>
    /// 技能id
    /// </summary>
    public readonly System.Collections.Generic.List<int> SkillList;
    /// <summary>
    /// 武器槽
    /// </summary>
    public readonly int WeaponSlotSkill;
    /// <summary>
    /// 护甲或其他槽
    /// </summary>
    public readonly int ArmorSlotSkill;
    /// <summary>
    /// 背包内
    /// </summary>
    public readonly int BagSlotSkill;
    /// <summary>
    /// 属性id
    /// </summary>
    public readonly int PropertyId;
    /// <summary>
    /// 详情
    /// </summary>
    public readonly string Des;
   
    public const int __ID__ = 1242142757;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemId:" + ItemId + ","
        + "evlack:" + Evlack + ","
        + "avlcmb:" + Avlcmb + ","
        + "skillList:" + Luban.StringUtil.CollectionToString(SkillList) + ","
        + "weaponSlotSkill:" + WeaponSlotSkill + ","
        + "armorSlotSkill:" + ArmorSlotSkill + ","
        + "bagSlotSkill:" + BagSlotSkill + ","
        + "propertyId:" + PropertyId + ","
        + "des:" + Des + ","
        + "}";
    }
}

}
