
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Rank : Luban.BeanBase
{
    public Rank(JSONNode _buf) 
    {
        { if(!_buf["rankId"].IsNumber) { throw new SerializationException(); }  RankId = _buf["rankId"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["subRank"].IsNumber) { throw new SerializationException(); }  SubRank = _buf["subRank"]; }
        { if(!_buf["subLevel"].IsNumber) { throw new SerializationException(); }  SubLevel = _buf["subLevel"]; }
        { if(!_buf["score"].IsNumber) { throw new SerializationException(); }  Score = _buf["score"]; }
        { if(!_buf["baseHp"].IsNumber) { throw new SerializationException(); }  BaseHp = _buf["baseHp"]; }
        { if(!_buf["basePower"].IsNumber) { throw new SerializationException(); }  BasePower = _buf["basePower"]; }
        { var __json0 = _buf["rewardScoreList"]; if(!__json0.IsArray) { throw new SerializationException(); } RewardScoreList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  RewardScoreList.Add(__v0); }   }
        { var __json0 = _buf["rewardGoldList"]; if(!__json0.IsArray) { throw new SerializationException(); } RewardGoldList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  RewardGoldList.Add(__v0); }   }
    }

    public static Rank DeserializeRank(JSONNode _buf)
    {
        return new Rank(_buf);
    }

    /// <summary>
    /// 段位id
    /// </summary>
    public readonly int RankId;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 段位
    /// </summary>
    public readonly int SubRank;
    /// <summary>
    /// 小等级
    /// </summary>
    public readonly int SubLevel;
    /// <summary>
    /// 积分
    /// </summary>
    public readonly int Score;
    /// <summary>
    /// 基础血量
    /// </summary>
    public readonly int BaseHp;
    /// <summary>
    /// 基础耐力
    /// </summary>
    public readonly int BasePower;
    /// <summary>
    /// 胜场积分列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> RewardScoreList;
    /// <summary>
    /// 金币获取列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> RewardGoldList;
   
    public const int __ID__ = 2539596;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "rankId:" + RankId + ","
        + "name:" + Name + ","
        + "subRank:" + SubRank + ","
        + "subLevel:" + SubLevel + ","
        + "score:" + Score + ","
        + "baseHp:" + BaseHp + ","
        + "basePower:" + BasePower + ","
        + "rewardScoreList:" + Luban.StringUtil.CollectionToString(RewardScoreList) + ","
        + "rewardGoldList:" + Luban.StringUtil.CollectionToString(RewardGoldList) + ","
        + "}";
    }
}

}
