
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Role : Luban.BeanBase
{
    public Role(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["specialItemIdList"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialItemIdList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SpecialItemIdList.Add(__v0); }   }
    }

    public static Role DeserializeRole(JSONNode _buf)
    {
        return new Role(_buf);
    }

    /// <summary>
    /// 职业表
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 特殊道具表,只能有一个在背包
    /// </summary>
    public readonly System.Collections.Generic.List<int> SpecialItemIdList;
   
    public const int __ID__ = 2552982;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "specialItemIdList:" + Luban.StringUtil.CollectionToString(SpecialItemIdList) + ","
        + "}";
    }
}

}
