
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Battle.TBGLConst TBGLConst {get; }
    public Battle.TBItem TBItem {get; }
    public Battle.TBProperty TBProperty {get; }
    public Battle.TBItemStar TBItemStar {get; }
    public Battle.TBRank TBRank {get; }
    public Battle.TBPlacingSkill TBPlacingSkill {get; }
    public Battle.TBGoodsStar TBGoodsStar {get; }
    public Battle.TBTreasureBox TBTreasureBox {get; }
    public Battle.TBRole TBRole {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TBGLConst = new Battle.TBGLConst(loader("battle_tbglconst"));
        TBItem = new Battle.TBItem(loader("battle_tbitem"));
        TBProperty = new Battle.TBProperty(loader("battle_tbproperty"));
        TBItemStar = new Battle.TBItemStar(loader("battle_tbitemstar"));
        TBRank = new Battle.TBRank(loader("battle_tbrank"));
        TBPlacingSkill = new Battle.TBPlacingSkill(loader("battle_tbplacingskill"));
        TBGoodsStar = new Battle.TBGoodsStar(loader("battle_tbgoodsstar"));
        TBTreasureBox = new Battle.TBTreasureBox(loader("battle_tbtreasurebox"));
        TBRole = new Battle.TBRole(loader("battle_tbrole"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TBGLConst.ResolveRef(this);
        TBItem.ResolveRef(this);
        TBProperty.ResolveRef(this);
        TBItemStar.ResolveRef(this);
        TBRank.ResolveRef(this);
        TBPlacingSkill.ResolveRef(this);
        TBGoodsStar.ResolveRef(this);
        TBTreasureBox.ResolveRef(this);
        TBRole.ResolveRef(this);
    }
}

}
