
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TreasureBox : Luban.BeanBase
{
    public TreasureBox(JSONNode _buf) 
    {
        { if(!_buf["rankId"].IsNumber) { throw new SerializationException(); }  RankId = _buf["rankId"]; }
        { if(!_buf["number"].IsNumber) { throw new SerializationException(); }  Number = _buf["number"]; }
    }

    public static TreasureBox DeserializeTreasureBox(JSONNode _buf)
    {
        return new TreasureBox(_buf);
    }

    /// <summary>
    /// 段位id
    /// </summary>
    public readonly int RankId;
    /// <summary>
    /// 总个数/h
    /// </summary>
    public readonly int Number;
   
    public const int __ID__ = 278517884;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "rankId:" + RankId + ","
        + "number:" + Number + ","
        + "}";
    }
}

}
